InitializeWorkspace

visdiff(...
    'C:\Users\Lenovo\Documents\adkeles\Matlab_MatlabAPI\trunk\Product Version\MatlabAPI Developer', ...
    'C:\Users\Lenovo\Documents\adkeles\Matlab_MatlabAPI\trunk\Test Version\MatlabAPI Developer'...
    )